### ISSUE TITLE
PHP fatal error on fresh install

### ISSUE THREAD

**Issue by ernilambar** [WordPress/sqlite-database-integration#1]
I get following PHP fatal error when I fresh install WP and activate the plugin.

```
[17-Jan-2023 15:24:06 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function wp_kses_post() in /Users/nilambarsharma/MampSites/jhilke/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-pdo-engine.php:1332
Stack trace:
#0 /Users/nilambarsharma/MampSites/jhilke/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-pdo-engine.php(1257): WP_SQLite_PDO_Engine->convert_to_columns_object()
#1 /Users/nilambarsharma/MampSites/jhilke/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-pdo-engine.php(470): WP_SQLite_PDO_Engine->process_results(Object(WP_SQLite_PDO_Driver))
#2 /Users/nilambarsharma/MampSites/jhilke/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(245): WP_SQLite_PDO_Engine->query('DESCRIBE wp_use...')
#3 /Users/nilambarsharma/MampSites/jhilke/wp-includes/class-wpdb.php(2854): WP_SQLite_DB->query('DESCRIBE wp_use...')
#4 /Users/nilambarsharma/MampSites/jhilke/wp-includes/functions.php(1805): wpdb->get_results('D in /Users/nilambarsharma/MampSites/jhilke/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-pdo-engine.php on line 1332

```

**Comment by aristath** [comment]
Thank you for catching this! Fixed in https://github.com/WordPress/sqlite-database-integration/commit/0771e20a56d88d393738b3e6ae87ecd35fb3f9c8 and a new version will be released on w.org in a few minutes 👍
