### ISSUE TITLE
Unknown drop type: INDEX

### ISSUE THREAD

**Issue by stuartlangridge** [WordPress/sqlite-database-integration#116]
`wp2static` tries to run this command

`DROP INDEX status ON wp_wp2static_jobs`

as part of setup. This plugin doesn't know how to handle that, it seems: I get the error (with formatting HTML removed)

```
MySQL query:
DROP INDEX status ON wp_wp2static_jobs
Queries made or created this session were:
* Executing: BEGIN | (no parameters)
* Executing: ROLLBACK | (no parameters)
Error occurred at line 3777 in Function <code>handle_error</code>. Error message was: Unknown drop type: INDEX.

Backtrace:
#0 ...path/to/webroot/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 ...path/to/webroot/wp-content/plugins/wp2static/src/JobQueue.php(28): WP_SQLite_DB->query('DROP INDEX stat...')
#2 ...path/to/webroot/wp-content/plugins/wp2static/src/Controller.php(110): WP2Static\JobQueue::createTable()
#3 ...path/to/webroot/wp-content/plugins/wp2static/src/Controller.php(136): WP2Static\Controller::activateForSingleSite()
...
```

**Comment by stuartlangridge** [comment]
I suspect this is because of https://github.com/WordPress/sqlite-database-integration/blob/e47669844e2c0f5d255e82b503d80526a7f8a9eb/wp-includes/sqlite/class-wp-sqlite-translator.php#L3217 which seems to understand DROP TABLE, DROP PROCEDURE, and DROP DATABASE, but not DROP INDEX.

However, https://github.com/WordPress/sqlite-database-integration/blob/e47669844e2c0f5d255e82b503d80526a7f8a9eb/wp-includes/sqlite/class-wp-sqlite-translator.php#L541 claims that DROP INDEX is a specific type of query that needs special support, although I can't find whether it actually _implements_ that special support anywhere.

**Comment by stuartlangridge** [comment]
(checking into this further, `CREATE INDEX` isn't supported either, it seems.

`Error message was: Unknown create type: INDEX.`

**Comment by JanJakes** [comment]
This was fixed in trunk and will be included in the 3.0 release.
