### ISSUE TITLE
Unknown operation: DEFAULT CHARACTER SET

### ISSUE THREAD

**Issue by eLearningTechie** [WordPress/sqlite-database-integration#144]
WordPress Playground could be very useful for educators and their students.
One interactive content plugin we use a lot in our learning management systems (e.g. Moodle) is the H5P editor (https://h5p.org/wordpress). I have tried using it on Playground, but even though the plugin installs just fine, the editor then fails to load. I suspect it's unable to connect to the H5P hub for some reason and thus can't retrieve the activity types.

The education community would be super grateful if someone could look into this and get it to work.

**Comment by bgrgicak** [comment]
Thank you for reporting this issue @eLearningTechie! 

> have tried using it on Playground, but even though the plugin installs just fine, the editor then fails to load. I suspect it's unable to connect to the H5P hub for some reason and thus can't retrieve the activity types.

When I tested the plugin I wasn't able to install it [because of the SQL error.](https://github.com/WordPress/sqlite-database-integration/issues/144#issuecomment-2268662861)

How are you able to install the plugin?
If you go to the browser console, are there any errors? If so, could you please share them here?

**Comment by eLearningTechie** [comment]
Dunno, with my browser (Chrome 126.0.6478.222) set to local storage and network access granted, I got this far:

![Screenshot 2024-08-13 10 00 14](https://github.com/user-attachments/assets/b753981a-7422-4abf-ace0-01c44d1f8f73)
![Screenshot 2024-08-13 09 59 39](https://github.com/user-attachments/assets/e75c4e87-24e7-4b31-afa7-94ed3cbc08dc)
![Screenshot 2024-08-13 09 59 09](https://github.com/user-attachments/assets/39c026e5-c964-48b8-a515-0a2cab2a27c3)

I only run into problems at the point where full-fat WP loads the external H5P hub / editor interface: 

Playground throws a blank
![Screenshot 2024-08-13 10 00 36](https://github.com/user-attachments/assets/08bf15b4-095c-4ef3-8ec5-3c63c8e858c4)

My regular self-hosted WP looks like this 
![Screenshot 2024-08-13 10 04 26](https://github.com/user-attachments/assets/f6ea72ae-4493-442c-a824-862ec0c8250c)

Something is preventing communications between the Playground WP and the H5P hubsite where the H5P editor lives.

----------
This is the entire console log from this morning's retry:

[13-Aug-2024 08:59:17 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>ALTER TABLE `wp_h5p_contents` DEFAULT CHARACTER SET utf8mb4</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 3939 in Function <code>handle_error</code>. Error message was: Unknown operation: DEFAULT CHARACTER SET.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-content/plugins/h5p/public/class-h5p-plugin.php(563): WP_SQLite_DB->query('ALTER TABLE `wp...')
#2 /wordpress/wp-content/plugins/h5p/public/class-h5p-plugin.php(473): H5P_Plugin::upgrade_120()
#3 /wordpress/wp-content/plugins/h5p/public/class-h5p-plugin.php(152): H5P_Plugin::check_for_updates()
#4 /wordpress/wp-includes/class-wp-hook.php(3): H5P_Plugin::activate(false)
#5 /wordpress/wp-includes/class-wp-hook.php(3): WP_Hook->apply_filters('', Array)
#6 /wordpress/wp-includes/plugin.php(2): WP_Hook->do_action(Array)
#7 /wordpress/wp-admin/includes/plugin.php(2): do_action('activate_h5p/h5...', false)
#8 /wordpress/wp-admin/plugins.php(2): activate_plugin('h5p/h5p.php', 'https://playgro...', false)
#9 {main}</pre>
 for query ALTER TABLE `wp_h5p_contents` DEFAULT CHARACTER SET utf8mb4 made by activate_plugin, do_action('activate_h5p/h5p.php'), WP_Hook->do_action, WP_Hook->apply_filters, H5P_Plugin::activate, H5P_Plugin::check_for_updates, H5P_Plugin::upgrade_120, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[13-Aug-2024 08:59:17 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>ALTER TABLE `wp_h5p_contents_libraries` DEFAULT CHARACTER SET utf8mb4</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 3939 in Function <code>handle_error</code>. Error message was: Unknown operation: DEFAULT CHARACTER SET.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-content/plugins/h5p/public/class-h5p-plugin.php(564): WP_SQLite_DB->query('ALTER TABLE `wp...')
#2 /wordpress/wp-content/plugins/h5p/public/class-h5p-plugin.php(473): H5P_Plugin::upgrade_120()
#3 /wordpress/wp-content/plugins/h5p/public/class-h5p-plugin.php(152): H5P_Plugin::check_for_updates()
#4 /wordpress/wp-includes/class-wp-hook.php(3): H5P_Plugin::activate(false)
#5 /wordpress/wp-includes/class-wp-hook.php(3): WP_Hook->apply_filters('', Array)
#6 /wordpress/wp-includes/plugin.php(2): WP_Hook->do_action(Array)
#7 /wordpress/wp-admin/includes/plugin.php(2): do_action('activate_h5p/h5...', false)
#8 /wordpress/wp-admin/plugins.php(2): activate_plugin('h5p/h5p.php', 'https://playgro...', false)
#9 {main}</pre>
 for query ALTER TABLE `wp_h5p_contents_libraries` DEFAULT CHARACTER SET utf8mb4 made by activate_plugin, do_action('activate_h5p/h5p.php'), WP_Hook->do_action, WP_Hook->apply_filters, H5P_Plugin::activate, H5P_Plugin::check_for_updates, H5P_Plugin::upgrade_120, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[13-Aug-2024 08:59:17 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>ALTER TABLE `wp_h5p_results` DEFAULT CHARACTER SET utf8mb4</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 3939 in Function <code>handle_error</code>. Error message was: Unknown operation: DEFAULT CHARACTER SET.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-content/plugins/h5p/public/class-h5p-plugin.php(565): WP_SQLite_DB->query('ALTER TABLE `wp...')
#2 /wordpress/wp-content/plugins/h5p/public/class-h5p-plugin.php(473): H5P_Plugin::upgrade_120()
#3 /wordpress/wp-content/plugins/h5p/public/class-h5p-plugin.php(152): H5P_Plugin::check_for_updates()
#4 /wordpress/wp-includes/class-wp-hook.php(3): H5P_Plugin::a
2VM213 jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 3.4.1
config-40887e56.js:1 [13-Aug-2024 08:59:44 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>SELECT hc.title AS title, hl.title AS content_type, GROUP_CONCAT(DISTINCT CONCAT(t.id,',',t.name) ORDER BY t.id SEPARATOR ';') AS tags, hc.updated_at AS updated_at, hc.id AS id, hc.user_id AS user_id, hl.name AS content_type_id
      FROM wp_h5p_contents hc
       LEFT JOIN wp_h5p_libraries hl ON hl.id = hc.library_id LEFT JOIN wp_h5p_contents_tags ct ON ct.content_id = hc.id
               LEFT JOIN wp_h5p_tags t ON ct.tag_id = t.id
               LEFT JOIN wp_h5p_contents_tags ct2 ON ct2.content_id = hc.id
      
      GROUP BY hc.id
       ORDER BY hc.updated_at DESC
       LIMIT 0, 20</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: SELECT hc.title AS title, hl.title AS content_type, GROUP_CONCAT(DISTINCT (t.id||:param0 ||t.name) ORDER BY t.id SEPARATOR :param1 ) AS tags, hc.updated_at AS updated_at, hc.id AS id, hc.user_id AS user_id, hl.name AS content_type_id
      FROM wp_h5p_contents hc
       LEFT JOIN wp_h5p_libraries hl ON hl.id = hc.library_id LEFT JOIN wp_h5p_contents_tags ct ON ct.content_id = hc.id
               LEFT JOIN wp_h5p_tags t ON ct.tag_id = t.id
               LEFT JOIN wp_h5p_contents_tags ct2 ON ct2.content_id = hc.id
      
      GROUP BY hc.id
       ORDER BY hc.updated_at DESC
       LIMIT 0, 20 | parameters: ,, ;</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 3939 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 near "ORDER": syntax error.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-includes/class-wpdb.php(3): WP_SQLite_DB->query('SELECT hc.title...')
#2 /wordpress/wp-content/plugins/h5p/admin/class-h5p-content-query.php(251): wpdb->get_results('SELECT hc.title...')
#3 /wordpress/wp-content/plugins/h5p/admin/class-h5p-content-admin.php(817): H5PContentQuery->get_rows()
#4 /wordpress/wp-includes/class-wp-hook.php(3): H5PContentAdmin->ajax_contents('')
#5 /wordpress/wp-includes/class-wp-hook.php(3): WP_Hook->apply_filters('', Array)
#6 /wordpress/wp-includes/plugin.php(2): WP_Hook->do_action(Array)
#7 /wordpress/wp-admin/admin-ajax.php(2): do_action('wp_ajax_h5p_con...')
#8 {main}</pre>
 for query SELECT hc.title AS title, hl.title AS content_type, GROUP_CONCAT(DISTINCT CONCAT(t.id,',',t.name) ORDER BY t.id SEPARATOR ';') AS tags, hc.updated_at AS updated_at, hc.id AS id, hc.user_id AS user_id, hl.name AS content_type_id
      FROM wp_h5p_contents hc
       LEFT JOIN wp_h5p_libraries hl ON hl.id = hc.library_id LEFT JOIN wp_h5p_contents_tags ct ON ct.content_id = hc.id
               LEFT JOIN wp_h5p_tags t ON ct.tag_id = t.id
               LEFT JOIN wp_h5p_contents_tags ct2 ON ct2.content_id = hc.id
      
      GROUP BY hc.id
       ORDER BY hc.updated_at DESC
       LIMIT 0, 20 made by do_action('wp_ajax_h5p_contents'), WP_Hook->do_action, WP_Hook->apply_filters, H5PContentAdmin->ajax_contents, H5PContentQuery->get_rows, WP_SQLite_DB->query, WP_SQLite_DB->print_error

2VM213 jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 3.4.1
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-fullscreen-bar.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-form.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-text.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-number.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-html.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-file-uploader.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-textarea.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-file.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-image.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-av.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-image-popup.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-boolean.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-group.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-list-editor.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-list.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-library.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-library-list-cache.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-selector-hub.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-select.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-dimensions.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-selector-legacy.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-none.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-coordinates.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-metadata-author-widget.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-metadata.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-pre-save.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/scripts/h5peditor-metadata-changelog-widget.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-editor-php-library/ckeditor/ckeditor.js?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/scope:0.5934848387342693/wp-content/plugins/h5p/h5p-php-library/styles/h5p-confirmation-dialog.css?ver=1.15.8:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()

**Comment by JanJakes** [comment]
This was fixed in trunk and will be included in the 3.0 release.
