### ISSUE TITLE
non-functional

### ISSUE THREAD

**Issue by a97115038** [WordPress/sqlite-database-integration#160]
Can you give me detailed installation steps? I copied DB.php to the wp-content root directory, and then started the installation prompting "There has been a critical error on this website."

**Comment by a97115038** [comment]
Warning: require_once(D:\wwwroot\192.168.100.5/constants.php): Failed to open stream: No such file or directory in D:\wwwroot\192.168.100.5\wordpress\wp-content\db.php on line 10

Fatal error: Uncaught Error: Failed opening required 'D:\wwwroot\192.168.100.5/constants.php' (include_path='.;C:\php\pear') in D:\wwwroot\192.168.100.5\wordpress\wp-content\db.php:10 Stack trace: #0 D:\wwwroot\192.168.100.5\wordpress\wp-includes\load.php(685): require_once() #1 D:\wwwroot\192.168.100.5\wordpress\wp-settings.php(132): require_wp_db() #2 D:\wwwroot\192.168.100.5\wordpress\wp-config.php(96): require_once('D:\\wwwroot\\192....') #3 D:\wwwroot\192.168.100.5\wordpress\wp-load.php(50): require_once('D:\\wwwroot\\192....') #4 D:\wwwroot\192.168.100.5\wordpress\wp-blog-header.php(13): require_once('D:\\wwwroot\\192....') #5 D:\wwwroot\192.168.100.5\wordpress\index.php(17): require('D:\\wwwroot\\192....') #6 {main} thrown in D:\wwwroot\192.168.100.5\wordpress\wp-content\db.php on line 10

**Comment by JanJakes** [comment]
> Can you give me detailed installation steps? I copied DB.php to the wp-content root directory

You only need to install and activate the plugin, and you'll be guided through a setup. Don't copy any files, the plugin activation will take care of that.
