### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function has() on null in /app/wp-includes/l10n.php:1268

### ISSUE THREAD

**Issue by sebastienserre** [WordPress/sqlite-database-integration#3]
Hello,

I've just tried your job and found a fatal error:

```
Fatal error: Uncaught Error: Call to a member function has() on null in /app/wp-includes/l10n.php:1268 
Stack trace: 
#0 /app/wp-includes/l10n.php(1303): _load_textdomain_just_in_time('sqlite-database...') 
#1 /app/wp-includes/l10n.php(187): get_translations_for_domain('sqlite-database...') 
#2 /app/wp-includes/l10n.php(299): translate('Queries made or...', 'sqlite-database...') 
#3 /app/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-pdo-engine.php(607): __('Queries made or...', 'sqlite-database...') 
#4 /app/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(252): WP_SQLite_PDO_Engine->get_error_message() 
#5 /app/wp-includes/class-wpdb.php(2854): WP_SQLite_DB->query('SELECT option_n...') 
#6 /app/wp-includes/option.php(312): wpdb->get_results('SELECT option_n...') #7 /app/wp-includes/functions.php(1766): wp_load_alloptions() 
#8 /app/wp-includes/load.php(771): is_blog_installed() 
#9 /app/wp-settings.php(160): wp_not_installed() 
#10 /app/wp-config.php(94): require_once('/app/wp-setting...') 
#11 /app/wp-load.php(50): require_once('/app/wp-config....') 
#12 /app/wp-admin/admin.php(34): require_once('/app/wp-load.ph...') 
#13 /app/wp-admin/index.php(10): require_once('/app/wp-admin/a...') 
#14 {main} thrown in /app/wp-includes/l10n.php on line 1268 

Fatal error: Uncaught Error: Call to a member function has() on null in /app/wp-includes/l10n.php:1268 
Stack trace: 
#0 /app/wp-includes/l10n.php(1303): _load_textdomain_just_in_time('sqlite-database...') 
#1 /app/wp-includes/l10n.php(187): get_translations_for_domain('sqlite-database...') 
#2 /app/wp-includes/l10n.php(299): translate('Queries made or...', 'sqlite-database...') 
#3 /app/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-pdo-engine.php(607): __('Queries made or...', 'sqlite-database...') 
#4 /app/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(252): WP_SQLite_PDO_Engine->get_error_message() 
#5 /app/wp-includes/class-wpdb.php(2854): WP_SQLite_DB->query('SELECT option_n...') 
#6 /app/wp-includes/option.php(312): wpdb->get_results('SELECT option_n...') 
#7 /app/wp-includes/option.php(191): wp_load_alloptions() 
#8 /app/wp-includes/l10n.php(63): get_option('WPLANG') 
#9 /app/wp-includes/l10n.php(139): get_locale() 
#10 /app/wp-includes/l10n.php(866): determine_locale() 
#11 /app/wp-includes/class-wp-fatal-error-handler.php(47): load_default_textdomain() 
#12 [internal function]: WP_Fatal_Error_Handler->handle() 
#13 {main} thrown in /app/wp-includes/l10n.php on line 1268
```
**Site Health Info:**
[site-health.txt](https://github.com/WordPress/sqlite-database-integration/files/10506930/site-health.txt)

The setting seems to say that i'm using SQLite, but I haven't lost my site setting and I didn't follow the installation wizard.

Regards

**Comment by aristath** [comment]
Hello @sebastienserre, thank you for reporting this!
Could you please provide some more details? When are you getting this error? Does it happen as soon as you activate the module? Is there some specific action that triggered it?

**Comment by sebastienserre** [comment]
Hello,

It happens when I click on "install SQLite Database" available at `/wp-admin/options-general.php?page=sqlite-integration`
https://www.loom.com/share/28f29165e85246a08f08bc8322dbf0b4

**Comment by aristath** [comment]
Ah OK, thank you for the clarifications.
You're using the standalone plugin from what I saw, and I just released the update, which - in theory - should fix this issue.
Unfortunately, I was unable to replicate your issue - which is why I'm saying that _it should fix the issue in theory_
Please update the plugin to v1.0.3, and let me know if that works for you 👍

**Comment by sebastienserre** [comment]
I confirm v1.0.2 is solving this issue.
