### ISSUE TITLE
Critical error on site health screen

### ISSUE THREAD

**Issue by mwt** [WordPress/sqlite-database-integration#37]
I get a critical error on the site health screen:

```
2023/05/19 04:09:39 [error] 273564#273564: *3 FastCGI sent in stderr: "PHP message: PHP Fatal
error:  Uncaught TypeError: property_exists():
Argument #1 ($object_or_class) must be of type
object|string, array given in ./html/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-translator.php:2427
Stack trace:
#0 ./html/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-translator.php(2427): property_exists()
#1 [internal function]: WP_SQLite_Translator->{closure}()
#2 ./html/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-translator.php(2424): array_filter()
#3 ./html/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-translator.php(2384): WP_SQLite_Translator->strip_sqlite_system_tables()
#4 ./html/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-translator.php(1381): WP_SQLite_Translator->get_information_schema_" while reading response header from upstream
```

This is on Debian Testing/Bookworm php8.2-fpm with nginx.

**Comment by chriskthomas** [comment]
My trace is a little longer

```
An error of type E_ERROR was caused in line 2427 of the file /srv/chriskthomas.com/html/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-translator.php. Error message: Uncaught TypeError: property_exists(): Argument #1 ($object_or_class) must be of type object|string, array given in /srv/chriskthomas.com/html/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-translator.php:2427
Stack trace:
#0 /srv/chriskthomas.com/html/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-translator.php(2427): property_exists()
#1 [internal function]: WP_SQLite_Translator->{closure}()
#2 /srv/chriskthomas.com/html/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-translator.php(2424): array_filter()
#3 /srv/chriskthomas.com/html/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-translator.php(2384): WP_SQLite_Translator->strip_sqlite_system_tables()
#4 /srv/chriskthomas.com/html/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-translator.php(1381): WP_SQLite_Translator->get_information_schema_query()
#5 /srv/chriskthomas.com/html/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-translator.php(736): WP_SQLite_Translator->execute_select()
#6 /srv/chriskthomas.com/html/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-translator.php(593): WP_SQLite_Translator->execute_mysql_query()
#7 /srv/chriskthomas.com/html/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(282): WP_SQLite_Translator->query()
#8 /srv/chriskthomas.com/html/wp-includes/class-wpdb.php(3099): WP_SQLite_DB->query()
#9 /srv/chriskthomas.com/html/wp-admin/includes/class-wp-site-health.php(3388): wpdb->get_results()
#10 /srv/chriskthomas.com/html/wp-admin/includes/class-wp-site-health.php(2469): WP_Site_Health->should_suggest_persistent_object_cache()
#11 /srv/chriskthomas.com/html/wp-admin/includes/class-wp-site-health.php(194): WP_Site_Health->get_test_persistent_object_cache()
#12 /srv/chriskthomas.com/html/wp-admin/includes/class-wp-site-health.php(139): WP_Site_Health->perform_test()
#13 /srv/chriskthomas.com/html/wp-includes/class-wp-hook.php(308): WP_Site_Health->enqueue_scripts()
#14 /srv/chriskthomas.com/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#15 /srv/chriskthomas.com/html/wp-includes/plugin.php(517): WP_Hook->do_action()
#16 /srv/chriskthomas.com/html/wp-admin/admin-header.php(118): do_action()
#17 /srv/chriskthomas.com/html/wp-admin/site-health.php(96): require_once('...')
#18 {main}
thrown
```

**Comment by aristath** [comment]
I believe this one has been fixed already 👍

**Comment by mwt** [comment]
@aristath I can confirm that it is fixed in the latest development version. So, it should work once you push the next release.
