### ISSUE TITLE
Moving a wp site made with SQLite Database Intergration

### ISSUE THREAD

**Issue by giannisg** [WordPress/sqlite-database-integration#44]
Hi to all,

I've succefuly created a site without using MySQL in a remote server, made my tests - and it's working (mostly) ok. Now, i need to transfer my database to local development, as a backup and a proof that my site is, finally, portable. 

I've installed Laragon, and downloaded all the content of my remore location - all the wordpress core files, the themes, the plugins, and the database file, everything as was in the server. I made sure that the SQLite 3 and PDO SQLite are checked on my Laragon's PHP extensions.

Sadly, it doesent work - i get a fatal error:

`Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 11 database disk image is malformed in C:\laragon\www\test\wp-content\plugins\sqlite-database-integration\wp-includes\sqlite\class-wp-sqlite-translator.php:379 Stack trace: #0 C:\laragon\www\test\wp-content\plugins\sqlite-database-integration\wp-includes\sqlite\class-wp-sqlite-translator.php(379): PDO->query('CREATE TABLE IF...') #1 C:\laragon\www\test\wp-content\plugins\sqlite-database-integration\wp-includes\sqlite\class-wp-sqlite-db.php(234): WP_SQLite_Translator->__construct(Object(PDO)) #2 C:\laragon\www\test\wp-includes\class-wpdb.php(773): WP_SQLite_DB->db_connect() #3 C:\laragon\www\test\wp-content\plugins\sqlite-database-integration\wp-includes\sqlite\class-wp-sqlite-db.php(31): wpdb->__construct('', '', '', '') #4 C:\laragon\www\test\wp-content\plugins\sqlite-database-integration\wp-includes\sqlite\db.php(64): WP_SQLite_DB->__construct() #5 C:\laragon\www\test\wp-content\db.php(37): require_once('C:\\laragon\\www\\...') #6 C:\laragon\www\test\wp-includes\load.php(666): require_once('C:\\laragon\\www\\...') #7 C:\laragon\www\test\wp-settings.php(124): require_wp_db() #8 C:\laragon\www\test\wp-config.php(96): require_once('C:\\laragon\\www\\...') #9 C:\laragon\www\test\wp-load.php(50): require_once('C:\\laragon\\www\\...') #10 C:\laragon\www\test\wp-blog-header.php(13): require_once('C:\\laragon\\www\\...') #11 C:\laragon\www\test\index.php(17): require('C:\\laragon\\www\\...') #12 {main} thrown in C:\laragon\www\test\wp-content\plugins\sqlite-database-integration\wp-includes\sqlite\class-wp-sqlite-translator.php on line 379`

Any ideas on what i'm i doing wrong and what should be the correct steps to make Wordpress finaly portable :)

**Comment by aristath** [comment]
Hey there @giannisg 
Looking at the error message you got, it looks like the database file was not properly copied :thinking: 
I'm not familiar with Laragon, but I was able to directly copy the database file using FTP in binary mode and did not have any issues with that. Maybe Laragon is treating the db file as an ASCII file instead of a binary? If that is the case, then on transfer the file will definitely be malformed
