### ISSUE TITLE
Accessing the Site Health page throws a critical error

### ISSUE THREAD

**Issue by dimkasta** [WordPress/sqlite-database-integration#46]
Hope this helps. Let me know if you need any more info about it. 
It's a simple Wordpress site with the Hello Elementor theme
PHP 8.2.11 on docker

``` php
Fatal error: Uncaught TypeError: property_exists(): Argument #1 ($object_or_class) must be of type object|string, array given in /sites/documentation.net.iconic.gr/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-translator.php:2427 
Stack trace: 
#0 /sites/documentation.net.iconic.gr/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-translator.php(2427): property_exists(Array, 'Name') 
#1 [internal function]: WP_SQLite_Translator->{closure}(Array, 0) 
#2 /sites/documentation.net.iconic.gr/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-translator.php(2424): array_filter(Array, Object(Closure), 1) 
#3 /sites/documentation.net.iconic.gr/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-translator.php(2384): WP_SQLite_Translator->strip_sqlite_system_tables(Array) 
#4 /sites/documentation.net.iconic.gr/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-translator.php(1381): WP_SQLite_Translator->get_information_schema_query('SELECT TABLE_NA...') 
#5 /sites/documentation.net.iconic.gr/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-translator.php(736): WP_SQLite_Translator->execute_select() 
#6 /sites/documentation.net.iconic.gr/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-translator.php(593): WP_SQLite_Translator->execute_mysql_query('SELECT TABLE_NA...') 
#7 /sites/documentation.net.iconic.gr/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(282): WP_SQLite_Translator->query('SELECT TABLE_NA...') 
#8 /sites/documentation.net.iconic.gr/wp-includes/class-wpdb.php(3127): WP_SQLite_DB->query('SELECT TABLE_NA...') 
#9 /sites/documentation.net.iconic.gr/wp-admin/includes/class-wp-site-health.php(3583): wpdb->get_results('SELECT TABLE_NA...', 'OBJECT_K') 
#10 /sites/documentation.net.iconic.gr/wp-admin/includes/class-wp-site-health.php(2654): WP_Site_Health->should_suggest_persistent_object_cache() 
#11 /sites/documentation.net.iconic.gr/wp-admin/includes/class-wp-site-health.php(194): WP_Site_Health->get_test_persistent_object_cache() 
#12 /sites/documentation.net.iconic.gr/wp-admin/includes/class-wp-site-health.php(139): WP_Site_Health->perform_test(Array) 
#13 /sites/documentation.net.iconic.gr/wp-includes/class-wp-hook.php(310): WP_Site_Health->enqueue_scripts('site-health.php') 
#14 /sites/documentation.net.iconic.gr/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array) 
#15 /sites/documentation.net.iconic.gr/wp-includes/plugin.php(517): WP_Hook->do_action(Array) 
#16 /sites/documentation.net.iconic.gr/wp-admin/admin-header.php(118): do_action('admin_enqueue_s...', 'site-health.php') 
#17 /sites/documentation.net.iconic.gr/wp-admin/site-health.php(96): require_once('/sites/document...') 
#18 {main} thrown in /sites/documentation.net.iconic.gr/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-translator.php on line 2427

There has been a critical error on this website. Please check your site admin email inbox for instructions.
```

**Comment by aristath** [comment]
It looks like this one had already been fixed on GitHub, but the update was never released in the .org repository.
I released v2.1.2 just now, so this should be fixed once you update the plugin 👍
